[workspace]

members = [
    "bot",
    "libtetris",
    "battle",
    "gui",
    "opening-book",
    "c-api",
    "compare",
    "optimizer",
    "opening-book/book-builder",
    "opening-book/pc-gen"
]