name: Build c-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup i686-pc-windows-msvc
      run: rustup target add i686-pc-windows-msvc
    - name: Build
      run: |
        cargo build --release -p c-api
        cargo build --release --target=i686-pc-windows-msvc -p c-api
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: win64
        path: target/release/cold_clear.dll
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: win32
        path: target/i686-pc-windows-msvc/release/cold_clear.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release -p c-api
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: target/release/libcold_clear.so

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cargo-ndk
      run: |
        cargo install cargo-ndk
        rustup target add aarch64-linux-android armv7-linux-androideabi
    - name: Build
      run: |
        export NDK_HOME=$ANDROID_NDK_PATH
        cd c-api
        cargo ndk --platform 21 --target armv7-linux-androideabi build --release
        cargo ndk --platform 21 --target aarch64-linux-android build --release
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android_armv7
        path: target/armv7-linux-androideabi/release/libcold_clear.so
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android_aarch64
        path: target/aarch64-linux-android/release/libcold_clear.so
